# config for the full dataset builder 

# patients ids
ids: [ 04762925, 00897741] # 04762925
test_ids: []
# sampling horizon
sampling_horizon: 7
# prediction horizon
prediction_horizon: 6
# scale
scale: 1
# outtype
outtype: "History"
# smooth
smooth: False
# target_weight
target_weight: 1
# standardize
standardize: True
# cutpoint (negative= take all the data)
cutpoint: -1
# augment type
augmentation: "GaussianNoise"
# augment factor
augmentation_params:
  num_augmentations: 1
  padding: "History"



