data:
  path: "./data/dataset_smooth.npy"
  n_train: 5000
  n_val: 10000
  n_test: 10000
  mean: 144.98204040527344
  std: 57.940860748291016
arima:
  p: 5
  d: 1
  q: 0
# gp_config
gp:
  kernel:
      constant: 1.0
      constant_bounds: [0.0001, 5000]
      rbf: 10
      rbf_bounds: [0.001, 1000]
      white_noise: 0.01
      white_noise_bounds: [0.00001, 1]
  n_restarts_optimizer: 50
svm:
  kernel: rbf
  C: 1.0
  gamma: "auto"

metrics:
  threshold: 80
