data_path: "./data/dataset_smooth_upsampled.npy"
data_mean: 127.836
# 144.98204040527344
data_std: 60.410
# 57.940860748291016
transfer_data_path: "./data/dataset_99908129.npy"
n_train: 3000000
n_val: 300000
n_test: 500000
batch_size: 128
buffer_size: 1000 # not used
epochs: 200
optimizer: "adam"
loss: "mae"
learning_rate: 0.0001
save_model: True
transfer_learning: True

model_config:
  model_type: "attn"
  cnn_config:
    n_conv_layers: 3
    filters: 160
    kernel_size: 3
    activation: "relu"
    input_shape: [7, 1]
    n_dense_layers: 2
    dense_size: 352
    output_shape: 6
  rnn_config:
    n_rnn_layers: 1
    rnn_units: 224
    n_dense_layers: 2
    dense_size: 64
    output_shape: 6
    input_shape: [7, 1]
  ar_rnn_config:
    units: 1
    unit_size: 64
    out_steps: 6
    num_features: 1
    dense_size: 64
    dense_units: 3
  attn_config:
    input_shape: [7, 1]
    output_shape: 6
    head_size: 448
    num_heads: 1
    ff_dim: 480
    num_transformer_blocks: 6
    mlp_units: [352, 352]
    mlp_dropout: 0.0
    dropout: 0.0
